/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import Head from "next/head";
import { useState } from "react";
import Modal from '../components/Modal'
import { RecipeCard } from "../components/RecipeCard";
import { z } from "zod"

const ApiResponseScheme = z.object({meals:z.array(z.object({
  idMeal: z.string(),
  strMeal: z.string(),
  strInstructions: z.string(),
  strMealThumb: z.string()
}))})

type Recipes = z.infer<typeof ApiResponseScheme>

export type Recipe = {
  idMeal: string;
  strMeal: string;
  strInstructions: string;
  strMealThumb: string;
}

const Home = (data: Recipes) => {
  


  console.log(data);  
  const [recipes, setRecipes] = useState<Recipes>(data)
  const [recipe, setRecipe] = useState<Recipe>()
  const [showModal, setShowModal] = useState<boolean>(false)

  const handleClick = () => {
    const randomIndex = Math.floor(Math.random() * 24) + 1
    console.log(recipes.meals[randomIndex]);
    setRecipe(recipes.meals[randomIndex])
    setShowModal(true)
  }
  return (
    <>
      <Head>
        <title>À Table 🍔</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#bef264] to-[#fff7ed]">
      
      <Modal showModal={showModal} setShowModal={setShowModal}>
          <div className="w-full overflow-hidden md:max-w-md md:rounded-2xl md:border md:border-gray-100 md:shadow-xl">
            <div className="flex flex-col items-center justify-center space-y-3 bg-white px-4 py-6 pt-8 text-center md:px-16">
            <RecipeCard randomRecipe={recipe} />
          </div>
      </div>
    </Modal>


        <div className="text-center container flex flex-col items-center justify-center gap-12 px-4 py-16 w-3/5">
          <h1 className="text-5xl font-extrabold tracking-tight text-slate-900 sm:text-[5rem]">
            Générateur aléatoire 
           de <span className="text-[#10b981]">recette</span>
          </h1>
          
          <div className="flex justify-center space-x-2">
          <div className="space-y-2">
            <button
              onClick={handleClick}
              className="inline-block px-4 py-3
              text-sm font-semibold text-center
              text-white uppercase transition
              duration-200 ease-in-out bg-[#10b981]
              rounded-md cursor-pointer
              hover:bg-[#059669] active:scale-90">
              Bon App !
            </button>
            </div>
            </div>
          </div>
      </main>
    </>
  );
};

export const getStaticProps = async () => {

  const recipes = await fetch("https://www.themealdb.com/api/json/v1/1/search.php?s=").then((response) => response.json())
  return {
    props: recipes
  }
}


export default Home;